"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['dcc.py']
DATA_FILES = []
OPTIONS = {
    'iconfile':'./logo/logo.icns'
}

setup(
    name='Dive Color Corrector',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
